# Generated by Django 3.2.8 on 2021-12-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_endereço_clientes_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendasprodutos',
            old_name='id_produto',
            new_name='id_produtos',
        ),
    ]
