# Generated by Django 3.2.8 on 2021-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rename_id_cliente_vendas_id_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
