# Generated by Django 3.2.8 on 2021-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='custo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='secao',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
